services:
  betterlytics-selfhost:
    image: ghcr.io/betterlytics/betterlytics-selfhost:v1.2.7
    env_file:
      - .env
      - ./base/.env.base
    restart: unless-stopped
    container_name: betterlytics-selfhost
    ports:
      - "${BIND_ADDRESS}:${HTTP_PORT}:80"
    volumes:
      - betterlytics_selfhost_postgres_data:/var/lib/postgresql/data
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - clickhouse_network

  clickhouse:
    image: clickhouse/clickhouse-server:25.5.2.47
    user: 101:101
    container_name: betterlytics-clickhouse
    restart: unless-stopped
    env_file:
      - .env
      - ./base/.env.base
    volumes:
      - betterlytics_selfhost_clickhouse_data:/var/lib/clickhouse/
      - betterlytics_selfhost_clickhouse_users:/etc/clickhouse-server/users.d/
      - ./base/clickhouse-config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./base/clickhouse-config/setup/:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
    networks:
      - clickhouse_network

volumes:
  betterlytics_selfhost_postgres_data:
  betterlytics_selfhost_clickhouse_data:
  betterlytics_selfhost_clickhouse_users:

networks:
  clickhouse_network:
    name: betterlytics_clickhouse_network
