services:
  proxy:
    build:
      context: ./base/proxy
      dockerfile: ./Dockerfile
    container_name: proxy
    hostname: proxy
    volumes:
      - ./base/static:/usr/share/nginx/html:ro
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully
      backend:
        condition: service_started
      dashboard:
        condition: service_started
    ports:
      - 5862:80
    networks:
      - proxy_network

  backend:
    image: ghcr.io/betterlytics/betterlytics-backend:main
    container_name: backend
    hostname: backend
    env_file:
      - .env
      - ./base/.env.base
    depends_on:
      init:
        condition: service_completed_successfully
    networks:
      - proxy_network
      - clickhouse_network

  dashboard:
    image: ghcr.io/betterlytics/betterlytics-dashboard:main
    env_file:
      - .env
      - ./base/.env.base
    restart: unless-stopped
    container_name: dashboard
    hostname: dashboard
    depends_on:
      init:
        condition: service_completed_successfully
    networks:
      - proxy_network
      - postgres_network
      - clickhouse_network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    user: 101:101
    container_name: clickhouse
    hostname: clickhouse
    restart: unless-stopped
    env_file:
      - .env
      - ./base/.env.base
    volumes:
      - clickhouse_prod_data:/var/lib/clickhouse/
      - clickhouse_prod_users:/etc/clickhouse-server/users.d/
      - ./base/clickhouse-config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./base/clickhouse-config/setup/:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
    networks:
      - clickhouse_network

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    env_file:
      - .env
      - ./base/.env.base
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
    networks:
      - postgres_network

  init:
    image: ghcr.io/betterlytics/betterlytics-initializer:main
    container_name: init
    hostname: init
    env_file:
      - .env
      - ./base/.env.base
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - postgres_network
      - clickhouse_network

volumes:
  clickhouse_prod_data:
  clickhouse_prod_users:
  postgres_prod_data:

networks:
  proxy_network:
  postgres_network:
  clickhouse_network:
