x-logging: &default-logging
  driver: "local"
  options:
    max-size: "10m"
    max-file: "5"

services:
  betterlytics-selfhost:
    image: ghcr.io/betterlytics/betterlytics-selfhost:latest
    env_file:
      - .env
      - ./base/.env.base
    restart: unless-stopped
    container_name: betterlytics-selfhost
    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${HTTP_PORT:-80}:80"
    volumes:
      - ./base/proxy:/etc/nginx/templates:ro
      - ./base/supervisord.conf:/etc/supervisor/conf.d/betterlytics.conf:ro
      - ./base/entrypoint.sh:/entrypoint.sh
      - betterlytics_selfhost_postgres_data:/var/lib/postgresql/data
      - betterlytics_selfhost_letsencrypt_certs:/etc/letsencrypt/live
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - clickhouse_network
    logging: *default-logging

  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    user: 101:101
    container_name: betterlytics-clickhouse
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/entrypoint-wrapper.sh"]
    env_file:
      - .env
      - ./base/.env.base
    volumes:
      - betterlytics_selfhost_clickhouse_data:/var/lib/clickhouse/
      - betterlytics_selfhost_clickhouse_users:/etc/clickhouse-server/users.d/
      - ./base/clickhouse-config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./base/clickhouse-config/entrypoint-wrapper.sh:/entrypoint-wrapper.sh
      - ./base/clickhouse-config/setup/:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
    networks:
      - clickhouse_network
    logging: *default-logging

volumes:
  betterlytics_selfhost_postgres_data:
  betterlytics_selfhost_clickhouse_data:
  betterlytics_selfhost_clickhouse_users:
  betterlytics_selfhost_letsencrypt_certs:

networks:
  clickhouse_network:
    name: betterlytics_clickhouse_network
